[build]
target = "mos-nes-cnrom"

[target.mos-nes-cnrom]
rustflags = [
    "-C", "link-arg=-Tsrc/link.ld",
    "-C", "link-arg=-Wl,--verbose",
    # export RUSTC_LOG=rustc_codegen_ssa::back::link=info
]

[unstable]
build-std = ["core", "alloc"]
