[package]
name = "brickgame"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = { version = "1.0"}

[features]
skip-legal = []
stress = []
debug = []
tas-compat = []

[dependencies]
nes = { path = "../nes"}
